---
    - name: Install Tomcat7 
      apt: pkg=tomcat7 state=latest
    
    - name: Install list of packages
      apt: pkg={{item}} state=latest
      with_items:
        - tomcat7-docs
        - tomcat7-admin
        - tomcat7-examples
        - tomcat7-user
         
    # - name: Tomcat users
    #  template: src=tomcat-users.xml.j2 dest=/etc/tomcat7/tomcat-users.xml mode=0664
    
    # - name: Max file size
    #  template: src=web.xml.j2 dest=/usr/share/tomcat7-admin/manager/WEB-INF/web.xml mode=0644
    