---
    # - copy: src=ldap.war dest=/home/{{user}}/ldap.war mode=0644

    # - name: Deploy application
    #  shell: wget --http-user=tomcat --http-password=tomcat 
    #        "http://localhost:8080/manager/text/deploy?war=file:/home/{{user}}/ldap.war&path=/ldap" -O -
    #  register: traces
    
    - name: Install Git 
      apt: pkg=git state=latest

    - name: Install Git 
      apt: pkg=openjdk-7-jdk state=latest
            
    - git: repo=https://github.com/quantum-dev/com.quantum.ldap.git dest=/var/lib/tomcat7/webapps/com.quantum.ldap
    
    - name: Install Ant 
      apt: pkg=ant state=latest
      
    - shell: ant chdir=/var/lib/tomcat7/webapps/com.quantum.ldap/com.quantum.wui.ldap/ 
    
    - shell: cp /var/lib/tomcat7/webapps/com.quantum.ldap/com.quantum.wui.ldap/package/ldap.war /var/lib/tomcat7/webapps/ldap.war